name: Logs for Netlify

on: pull_request
      
jobs:
  logs4netlify:
    name: Logs for Netlify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy Logs
      uses: bdougie/loglify@actions
        env:
          GITHUB_TOKEN: ${{ secrets.DOUGIE_TOKEN }}
